version: '2.2'
services:
  mysql-singleton:
    image: prom/prometheus:v2.12.0
    container_name: mysql-singleton
    entrypoint:
      - MYSQL_ROOT_PASSWORD=123456
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - docker-net

networks:
  docker-net:
    external: true