version: '2.2'
services:
  mysql-singleton:
    image: mysql:8.0
    container_name: mysql-singleton
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - local-net

networks:
  local-net:
    external: true
